on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set git config
      run: |
        git config --global user.email "noreply@bluebrown.github.io"
        git config --global user.name "GitHub Actions"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Release extension to github and azure marketplace
      run: npm run release
      env:
        VSCE_PAT: "${{ secrets.VSCE_PAT }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
